### ISSUE TITLE
I meet an error, when I use xilinx_u250_xdma_201830_2 platform

### ISSUE THREAD

**Issue by Microdent** [Xilinx/xup_vitis_network_example#8]
In your Readme.md, xilinx-u250-gen3x16-xdma-3.1-202020-1 is not supported by Vitis 2020.1. So I changed to the Xilinx_u250_xdma_201830_2 platform.

But I meet the following problem when using the Xilinx_u250_xdma_201830_2 platform:
![vnx_error0](https://user-images.githubusercontent.com/33905380/102849361-f649bf00-4451-11eb-9f38-f6334c494b91.png)
![vnx_error1](https://user-images.githubusercontent.com/33905380/102849375-fba70980-4451-11eb-92ec-6f106422c887.png)

So I try to use Vitis 2020.2 + xilinx-u250-gen3x16-xdma-3.1-202020-1 to run this example, but there are some tcl scripts were made for Vivado 2020.1.
Could you please help with me run this example on Alveo U250 Borad?

**Comment by mariodruiz** [comment]
My apologies, the README is not clear. `xilinx-u250-gen3x16-xdma-3.1-202020-1` is supported by the project. The repository as it is does not support the platform.

To generate the xcbin for this platform I suggest to do the following.
1. Run the make command to create xclbin with Vitis 2020.1, this will fail because the platform is only supported in Vitis 2020.2. This is fine, as long as all the xo files are created.
2. Run the make command using Vitis `2020.2` and XRT `2.8.*`, this step should generate the xclbin without a problem.

In order for the platform to be fully supported, the synthesis process of the HLS IP cores of the network layer needs to be ported to Vitis HLS. This process may take some time.

**Comment by Microdent** [comment]
@mariodruiz , the xclbin is generated successfully, thank you!

**Comment by lycosdae** [comment]
Dear Sir,
I meet a similar error with u200. 
![image](https://user-images.githubusercontent.com/6982075/106574014-55ccdb80-6575-11eb-8b97-795d2e4a9443.png)
Will there be any changes to make this example support u200?

**Comment by mariodruiz** [comment]
Alveo U200 is not supported because the current Alveo U200 shell does not exposes GT pins to the user logic. Until a new shell arrives, I am afraid the U200 is out of the picture for VNx. 

This table described what is supported https://github.com/Xilinx/xup_vitis_network_example#support
